spring:
  profiles: Dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: ${dbname}
    password: ${dbpassword}
     
  jpa:
      show-sql: true  
      hibernate:
        ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail: 
    host: smtp.gmail.com
    port: 587
    username: ${mailusername}
    password: ${mailpassword}
#  amazonProperties:
#    endPointUrl: 
#    accessKey: ${awsaccessKey}
#    secretKey: ${awssecretKey}
#    bucketName: ${awsbucketname}
    
  
          
 
    